version: '3'

services:
  web:
    image: lifeoverflow.azurecr.io/fullstack-web
    restart: always
    environment:
      - REACT_APP_API_URL
    ports:
      - "3000:3000"   
    tty: true      
    depends_on:
      - api    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.rule=Host(`fullstack.$MY_DOMAIN`)"
      # - "traefik.http.routers.web.tls.certresolver=lets-encr"
  api:
    image: lifeoverflow.azurecr.io/fullstack-api
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "3001:3001"        
    depends_on:
      - db      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`api.$MY_DOMAIN`)"
      # - "traefik.http.routers.api.tls.certresolver=lets-encr"      
  db:
    image: postgres:12.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg-data-azure:/var/lib/postgresql/data/
volumes:
    pg-data-azure:

networks:
  default:
    external:
      name: $DEFAULT_NETWORK    